### ISSUE TITLE
Todo list for password sharing

### ISSUE THREAD

**Issue by brantje** [brantje/passman#102]
Stuff needed for sharing
===
- [x] Warning when sharing over non-https connections. Although it should be pretty secure MITM its always a bad thing
- [ ] Add a way to upload a pre-generated user private and public key
- [ ] Fill this with stuff left to do in sharing
- [ ] Lazy load the sharing 
- [x] Public / Private RSA key generation on the client
- [ ] User listing and filtering
- [ ] Group listing and filtering
- [ ] Save method for the keys
- [ ] Random sharing key generation
- [ ] Sharing multi-user operability
- [ ] Sharing with groups ? (think a bit more deeply about this)
- [ ] Server key RSA exange system
- [ ] Hook on delete user
- [ ] Hook on delete group
- [ ] Hook on user removed from group
