### ISSUE TITLE
Todo list for sharing branch

### ISSUE THREAD

**Issue by animalillo** [brantje/passman#131]
This is the stuff planed so far for the sharing branch before it can be merged into master

Frontend
===
- [ ] A way to generate and renew the sharing keys
- [ ] A way to visualize the sharing RSA keys
- [ ] Sharing action that allows to select who to share the key with
- [ ] Visual indication of shared items
- [ ] Warning when sharing over untrusted connections (non ssl, maybe even with invalid certificate?)

Javascript
===
- [ ] RSA Key generation
- [ ] Saving and retrieving current user key
- [ ] RSA Private key encryption before saving
- [ ] Getting other users public keys
- [ ] Filtering the shared items from the rest to process them in a different way
- [ ] Processing sharing requests from other users
- [ ] Handling re shared items
- [ ] Enabling / Disabling sharing capabilities according to admin settings.

PHP
===
- [ ] Allow the user to save the keys
- [ ] Allow the user to get the keys
- [ ] Allow other users to get the keys, making sure the private keys are stripped out
- [ ] Share item method
- [ ] Get pending share requests

Backend (admin)
===
- [ ] Menu to set a minimum key size forced by the OC Instance administrator.
- [ ] Option to enable sharing over untrusted connections (non-ssl) (disabled by default).

Future features (not necessarily done before merging on master): 
- [ ] Group sharing
- [ ] Public link sharing
- [ ] Public link with password unlocking or allowing to include an unlocking key on the url, should study options
- [ ] Permission control (edit, re-share, maybe others).
- [ ] Option to allow the user to set his custom generated key pair, probably checking key length so that it matches the server minimum size.
- [ ] Old key versions deletion.

As a side note, i'm probably missing some points that needs to be done, because i'm writting this slightly late and a lil tired, so there it goes. Now i'll mark the spots that are ready.

Any ideas? Suggestions? Features? Questions? Anything? It's welcome on the comments below!

**Comment by ib54003** [comment]
any news here? :)

**Comment by animalillo** [comment]
Still working on it, but I don't have too much time in a row, Although I'll try to give a push this week.

**Comment by ib54003** [comment]
ok cool ;)

**Comment by ib54003** [comment]
any news?
