### ISSUE TITLE
Todo list for master branch (V 2.0) [$37]

### ISSUE THREAD

**Issue by brantje** [brantje/passman#56]
For the [angularJS](https://github.com/brantje/passman/tree/angularjs) branch.

Frontend
===
- [x] Rename show-hide password directive
- [x] Replace delete icon with a menu for (deletion, perm deletion, etc).
- [x] Remove items
- [x] Notification with 'xxx deleted [undo]' which undo the soft removal.   
Create global function that calls the angularjs function.
- [x] First run for new users
- [x] List removed items
- [x] Permanently delete items
- [x] Add files
- [x] Download files
- [x] Make use of [password-generator](https://github.com/bermi/password-generator)
- [x] Setting minimum password score on tag
- [x] Setting number of days before passwords expires on tag
- [x] Edit / remove custom fields
- [x] Ability to choose if an custom field is hidden by default
- [x] Remove files
- [x] Expire items
- [x] Custom icons
- [x] Replace angular-storage with http://www.jstorage.info/
- [x] Settings dialog 
- [x] Search 
- [x] Order newly created items
- [x] Fix importers
- [x] Look into csv export (and other exports) (Fields: Label, email, username, password, url)   
Added CSV, json and xml export.
- [x] add Bytes to humanSize filter -> https://gist.github.com/thomseddon/3511330
- [x] Add password est. crack time.
- [x] Fix bookmarklet (as in #58)
- [x] Split app.js into separate files 
- [x] Password strength scanner: Loop passwords, display those with a crack time less than $time (can be configured)
- [x] Change passman password   
- [x] Add a OTP generator (for services like: google, github, etc) [Example](http://jsfiddle.net/nt18yhmL)
- [x] Enter as default OK action in the master password prompt
- [x] Sort the item tags alphabetical   
- [x] Fix filterin on passwords at activity app
- [ ] Hook on delete user (clean up database)   
- [ ] Add passpack import   
- [x] On passman pw change, update all revisions with new pw   
- [x] Add last_changed proptery
- [x] Double appearing of save / close buttons in FF

Change history
===
- [x] Menu to show the changes and who made them
- [x] Some way to store the backups
- [x] A way to rollback changes

Activities
===
- [x] Item expires
- [x] Item shared
- [x] Item soft deleted
- [x] Item hard deleted
- [x] Item recovered
- [x] Item renamed

Example how to: http://pastebin.com/RkLNuZZC   
Also see: https://github.com/owncloud/activity/issues/195   

Admin page
======================

- [x] Add field key length for server (1024,2048,4096)
- [x] Add field length limit for client (1024,2048,4096) (needed?)
- [x] Add a way to upload a pre-generated server private and public key
- [x] Add option to disable sharing over non-https connections

**Comment by animalillo** [comment]
Sharing specifics: #131
